### ISSUE TITLE
High levels of radiation when looking at the README.md file

### ISSUE THREAD

**Issue by AlvaroMartinezR** [roboticslab-uc3m/teo-gazebo#4]
The title is self-explanatory. I literally got cancer looking at the readme file.

**Comment by rsantos88** [comment]
![image](https://user-images.githubusercontent.com/15872457/36305880-c5226578-1315-11e8-88ca-9baf5dd14ac4.png)

**Comment by RaulFdzbis** [comment]
Improves have been made in https://github.com/roboticslab-uc3m/teo-gazebo/commit/6c31e07fe0af3489f9a031d3bd698813d87dc004 regarding this issue.

Just as a note, for next issues **please** refer [here]( https://github.com/roboticslab-uc3m/developer-manual/blob/01870d8509ad006279e07d38a6f28bd3dc0b5f51/asking-questions.md) to see some tips of how to open an issue. Knowing how to correctly open an issue will greatly increase the chances of solving that issue.

@rsantos88 "thank you" for your contribution, but next time please add some caption to the image or some inside of what you are trying to say with it. You know  that "1 picture worth 1000 thousands words" is not always true.

**Comment by David-Estevez** [comment]
Good Friday issue! 😂😂

**Comment by rsantos88** [comment]
@RaulFdzbis is not always true but "a buen entendedor, pocas palabras bastan" :laughing:
